all: bubble-sort insertion-sort merge-sort quick-sort selection-sort

bubble-sort: bubble-sort.cpp Makefile output.txt
	g++ bubble-sort.cpp -o bubble-sort && ./bubble-sort >> output.txt

insertion-sort: insertion-sort.cpp Makefile output.txt
	g++ insertion-sort.cpp -o insertion-sort && ./insertion-sort >> output.txt

merge-sort: merge-sort.cpp Makefile output.txt
	g++ merge-sort.cpp -o merge-sort && ./merge-sort >> output.txt

quick-sort: quick-sort.cpp Makefile output.txt
	g++ quick-sort.cpp -o quick-sort && ./quick-sort >> output.txt

selection-sort: selection-sort.cpp Makefile output.txt
	g++ selection-sort.cpp -o selection-sort && ./selection-sort >> output.txt